### ISSUE TITLE
Clicking on a Post in the Overview overrides the thread's ID

### ISSUE THREAD

**Issue by tylerhcarter** [tylerhcarter/Triton#2]
After you click a post on the overview menu, refreshing brings you to the home screen.

This is mainly because we use the hash to identify what thread you are on. We should upgrade to a better system with a different syntax such as:

```
#<thread-id>/<post-id>
#0702147a-09fe-04bb-2656-1bf11b796464/7c83fa5c-b5f8-aff2-b0e8-7268d0736fb4
```

**Comment by lucjon** [comment]
Is this not fixed now?

**Comment by tylerhcarter** [comment]
Yes, it is fixed.
